name: projetosocial
description: "projeto para posta campanhas de arrecadação e aonde doar e oque doar"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.2
  provider: ^6.1.0
  uuid: ^4.5.1
  supabase: ^2.6.3
  intl: ^0.18.1
  envied: ^0.3.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  envied_generator: ^0.3.0
  build_runner: ^2.4.6

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true